name: Test
on:
  push:
  pull_request:
jobs:
  test:
    if: github.event_name != 'pull_request' || github.head_ref != 'devel'
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    name: py${{ matrix.python }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: setup
        run: |
          pip install poetry && poetry install
      - name: test
        continue-on-error: true
        run: poetry run pytest --cov=pydantic_argparse_builder --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: pytest
          name: pydantic_argparse_builder
          fail_ci_if_error: true
          verbose: true
